# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Custom"
license = "MIT"
licenselink = "https://github.com/0x8b/hub/blob/main/LICENSE"
description = ""
homepage = ""
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.112.4"

[author]
  name = "Mariusz Gumienny"
  homepage = "https://github.com/0x8b/"

[original]
  name = "Aditya Telange"
  homepage = "https://github.com/adityatelange/"
